### ISSUE TITLE
Add Store Tab to Settings Modal

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#255]
![image](https://cloud.githubusercontent.com/assets/1584275/21630734/03c5fd54-d202-11e6-8da6-222949fb5dfa.png)

The Store tab sets data used by vendors.

## Functional Requirements
- [x] A control to set the store to on or off. This control shows the current state of this setting. 
- [ ] A list of moderators that have currently been selected for the store. 
    - The design of the selected list is assumed to be similar to the browsing list (TBD)
    - Each moderator in the list has a button to remove them from the list.
- [x] A button to browse available moderators.
- [ ] When clicked, a list of available moderators is shown.
- [ ] Each moderator has the following available interactions:
    - [ ] A select button. When clicked, a popup/tooltip is shown with the terms of service, a cancel button and an agree button. Clicking the cancel button closes the tooltip, clicking agree the moderator is marked as selected. 
    - [ ] A button to add a moderator by handle or ID. When clicked, it will show a moderator card, with the option to select that moderator (identical to a moderator in the browse list). If the handle/guid profile comes back as not a moderator, a message should be shown that they are not a moderator.
- [ ] A save button. Clicking this button will save the current changes. 

## Data
- moderators, an array of guids, from the Settings API (stored in the settings model).
- the list of available moderators the get moderators API.
- vendor, a boolean, from the Profile API (stored in the profile model).
- each moderator loaded will need to make a call to IPFS to get it's profile data

## TODOs
- update the designs to indicate the store is off when the user is looking at their own listings
- update the designs to show what happens when a moderator is added by handle/guid.
- on backend, store the listings in a non-public folder when the store is deactivated, so the user can still look at and modify their own listings.
