### ISSUE TITLE
Add Inventory and Variants to Listings [Rough Draft]

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#302]
### Inventory
- [ ] in the edit listing screen, there should be a select list to select whether to track the inventory for this listing. 
    -[ ] The select list has the following options:
    - "Do not track inventory" [this is the default]
    - 'Track Inventory (Fixed Amount)"
    - "Track Inventory (By Variant)"
- [ ] if inventory is tracked by fixed amount, a Quantity field will be visible.
    - [ ] the Quantity field is the inventory for the listing.
-[ ] if inventory is tracked by variant, there must be at least one variant to save this listing.
-[ ] if inventory is tracked by variant, and no variants have been added, show a message instead of the grid "You haven't added any variants. Add some above."
- [ ] set maximum on the quantity inputs so a number that would be too big for JavaScript can't be entered (suggestion: use a text input and limit the characters). 

### Variants 
- [ ] there is a button to add a variant. It is always below any variant control sets.
    - [ ] when clicked, one variant control appears below any current variants
        - [ ] each control has an input for the name of the variant
        - [ ] each control has an input for options of the variant. This is a tag list.
            -[ ] if the tags wrap, the container should grow vertically.
            -[ ] there is a minimum of one option per variant.
        - [ ] each control has a delete button, which will delete the variant
- [ ] the variant gird is shown once at least one variant have been added.
    - [ ] the table has one row for every combination of variants (ie: if there is one variant with 2 options, and one with 3 options, there will be 6 rows).
    - [ ] each row has a surcharge input, which accepts a price in the user's currency.
    - [ ] each row has a total price field, which is the listing price plus the surcharge. If the surcharge is changed, the total price should update when the surcharge input loses focus.
    - [ ] each row has a quantity input, which accepts a number from 0 to (max JS can handle). 
    - [ ] each row has a checkbox to disable tracking inventory on a variant (the value is -1, which is infinite).  
    - [ ] the grid should have a max height equivalent of 8 rows, after that it should have a scroll bar.
- [ ] on the listing details screen, there should be one select box for each variant, above the Buy Now button.
- [ ] when a variant is selected, the price should update to add the variant surcharge.   

## ToDos
- update server to handle tracking one pool of inventory while still having variants (example: you have 100 shirts, and you will print one of 3 designs [variants] on each)
- update designs so variant grid is always visible, so surcharges can be entered even if inventory isn't tracked.
- update designs to remove the track inventory by variant checkbox.

### Inventory not being tracked, no variants:
![image](https://cloud.githubusercontent.com/assets/1584275/22083008/0c920c4c-dd98-11e6-8b9b-17fe1b0ce2ef.png)

### Inventory tracked overall, user just clicked the add variant button
![image](https://cloud.githubusercontent.com/assets/1584275/22082927/ca2f01f2-dd97-11e6-99c0-e04fe2a3b8b2.png)

### Inventory being tracked, two variants added
![image](https://cloud.githubusercontent.com/assets/1584275/22082892/a41324c6-dd97-11e6-8d21-e740ced42bfb.png)

**Comment by jjeffryes** [comment]
This was completed by #402
