### ISSUE TITLE
Add Coupons

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#303]
## Functional Requirements

- [ ] There is a button to add coupons
    - [ ] When clicked, it will add a coupon control set under the last current 
- [ ] Each coupon control set has the following controls:
    - [ ] A title field (max length of 70)
    - [ ] A Coupon Code field (a string, what is the max character length?)
        - [ ] The coupon code must be unique to this listing
    - [ ] A control to select percentage or fixed discount. When one is selected, the inputs for the percentage or fee appear/disappear as appropriate. 
    - [ ] A Discount field (0.01 to 100 Number as a percentage, cannot be negative)
    - [ ] Fixed fee (must be positive, cannot be higher than the item price)
    - [ ] A delete button that deletes the control set.
- [ ] When the checkout process is completed, the coupon can be added for the discount to be applied to the transaction.

## Data
-[ ]  The server will need the ability to track which coupon codes are associated with 

## TODOS
- Revise the design to include switching between percentage and fixed fee
- Add server capability to retrieve coupon codes based on hashes from the contract.

### No coupons
![image](https://cloud.githubusercontent.com/assets/1584275/21910119/b4550c86-d8e8-11e6-9150-249f9a106223.png)

### Coupons added
![image](https://cloud.githubusercontent.com/assets/1584275/21910083/90f6638e-d8e8-11e6-8694-2f4eb661d5a7.png)

**Comment by morebrownies** [comment]
The coupon prototype can be found here: https://invis.io/7YA6LOSPZ#/216042311_Openbazaar-Return-Policy-Default
