### ISSUE TITLE
Add Wallet Functionality

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#348]
![image](https://cloud.githubusercontent.com/assets/1584275/22670334/b502b7b6-ec96-11e6-8554-e9436ad53cf8.png)

![image](https://cloud.githubusercontent.com/assets/1584275/22670321/a6a7e696-ec96-11e6-8af0-068c95527aca.png)

The wallet is a modal that appears when the wallet icon in the navigation bar at the top of the app is clicked.

### General and Left Sidebar
- [ ] If the user's currency is set to a fiat currency, the current value of one bitcoin in that currency is displayed.
- it should be possible to use the existing bitcoin ticker view for this ticker.
- [ ] The current total amount of bitcoin being held in the user's account is shown.
- [ ] If the user's currency is set to a fiat currency, the current value of the bitcoin in the user's wallet is also shown in that fiat currency.
- [ ] A method of calculating the size of the currency displayed, and shrinking the font if necessary, should be implemented. Consider a library that can do this automatically.
- [ ] The total number of transactions in the user's database is shown.
- [ ] Any errors from the server are shown in a generic error modal.
- [ ] There is a Receive Money button.
    - [ ] When clicked, the Send Money section is replaced with the Receive Money section.

### Receive Money Section
- [ ] This will call the wallet/address api to retrieve an address
- [ ] A new address should be generated each time this Receive Money button is clicked.
- [ ] A QR code to send money to the user's wallet is shown.
- [ ] The address used in the QR code is shown.
- [ ] When the address is clicked, it should be copied to the system clipboard, and a copied indicator should be shown (identical to what is used elsewhere, such as the Donate tab in the About modal).
- [ ] A Need Bitcoin? link (the href is the need bitcoin page on openbazaar.org. It should open in the user's browser).
- [ ] The Receive Money button is replaced with a Send Money button to switch back to that section.
- [ ] The Cancel button will return to the Send Money section.

### Send Money section:
- [ ] It has a To field, that accepts a bitcoin address. 
    - [ ] The bitcoin address should be validated, and the user warned if it is not valid (this will be a standard form error).
- [ ] It has an amount field.
    - [ ] There is a select element to change the currency type. This works like the one in Settings/Moderation or the Edit Listing modal.
- [  ] Bitcoin and the user's fiat currency should be the first options in the select list, with a line under them if possible (this might be doable with select groups). 
- [ ] It has a Note field for adding a note to the transaction.
- [ ] It has a Clear button to clear the data in the Send Money inputs.
    - [ ] The Clear button is disabled until data has been entered in at least one field.
- [ ] It has a Send button that will send bitcoin based on the data in the Send Money inputs.
    - [ ] There will be a confirm step after the send button is clicked (design pending)

### Transactions section:
- [ ] The 20 most recent transaction are shown.
    - [ ] If the user scrolls, more are loaded 20 at a time.
    - [ ] The transactions section has a max height, and the transactions scroll within it.
    - [ ] The transactions are the same as the ones in the transactions screen.
    - [ ] If new transaction data is available, a refresh message will appear. Clicking the link in the message will refresh the transaction section, and query the API to update the current wallet total.

### Each Transaction:
- [ ] It shows an icon for either in progress, completed, or dead based on the number of confirmations. If the number of confirmations is -1, it is considered dead.
- [ ] If the state is dead, the confirmation text says "transaction stuck").
- [ ] It shows the fiat value of the transaction (if the user's currency is fiat).
- [ ] It shows the btc value of the transaction (if the user's currency is fiat, both fiat and btc are shown).
- [ ] It shows how long ago, rounded up, the transaction was (1 hour, 2 days, etc.). This will be calculated from the transaction's time stamp. We'll use whatever the rounding rules are in the library we use (probably moment.js).
- [ ] It shows the number of confirmations the transaction has.
- [ ] It shows any note attached to the transaction if it was a Send Money transaction the user sent to someone else.
- [ ] The transaction ID is shown truncated, if clicked on the ID is copied to the clipboard. A "copied" indicator should be shown.
- [ ] A View Details button that will open this transaction externally on the blockchain.info website.
- [ ] If the transaction has zero confirmations, it is older than 30 minutes, and it is an incoming payment, the Retry Payment button is visible.
    - if possible, this button will be available to the sender and receiver. 
    - there will be a flag in the server data designating whether the transaction can have a retry button. 
    - [ ] On hover, an arrow box will be shown with the following features:
    - [ ] A message explaining that a new transaction will be created with a higher fee.
        - the estimation API will provide the estimated cost of the new fee, and it will be displayed.
    - [ ] A Cancel button that will remove/hide the arrow box.
    - [ ] A Send button that will resend the payment.
    - [ ] If the Send button is clicked and a confirmation has come in since the data was last loaded, the server will return an error. It should be shown in a generic error modal.	

## Data
- a bitcoin address to deposit funds in the user's own wallet can be obtained from the wallet api (wallet/address).
- the Send Money functionality uses the wallet/spend API.
- a web socket will be provided that sends a message when new transaction data is available.

# TODOs

### Server
- create transactions API, with pagination
    - each transaction will need a timestamp
    - if possible, each transaction should have a retry-able true/false value
- create a retry fee estimation API
- errors will need error codes so they can be translated

**Comment by cpacia** [comment]
> When clicked, the Open button will open the bitcoin address in an external wallet.

I don't think this is really necessary. A wallet opening another wallet is weird and I've never really seen any do that.

**Comment by cpacia** [comment]
> It has a To field, that accepts a handle, guid, or Bitcoin address

Just bitcoin address per today's discussion.

**Comment by cpacia** [comment]
> It shows the other party's avatar.
Only possible when the transaction is part of an order. Otherwise there should probably be some kind of default image (different from default avatar?)

**Comment by jjeffryes** [comment]
>>> I don't think this is really necessary. A wallet opening another wallet is weird and I've never really seen any do that.

The designs were updated since I wrote that to remove the button, I'll revise the reqs.

**Comment by jjeffryes** [comment]
This was completed.
