### ISSUE TITLE
Add Chat Functionality to the Chat Sidebar

### ISSUE THREAD

**Issue by jjeffryes** [OpenBazaar/openbazaar-desktop#354]
The chat sidebar should show your conversations and allow the continuation of any past conversation. New conversations should appear in the chat sidebar.

### Chat Sidebar Conversation List
- [ ] Show a vertical stack of avatars. Each avatar represents a conversation with the other user whose avatar is shown.
- [ ] The stack is ordered by most recent message.
- [ ] There should be an indicator of how many unread messages are not visible (scrolled off screen).
    - [ ] If the conversation has unread messages, a badge with a number equal to the number of unread messages is shown on top of the avatar.
    - [ ] Clicking on the avatar or the first message to the right of the avatar, will load the conversation in the Current Conversation Section using the ob/chatmessages api (send it peerID and an empty subject, with pagination).
    - [ ] When the conversation is active, the unread message badge is removed, and the unread messages are marked as read (using the markchatasread endpoint).
    - [ ] When the conversation is active, the message to the right of the avatar is emphasized with a darker/thicker border.
- [ ] To the right of each avatar is a truncated handle or guid, and the first few words of the last message from that user (the actual last message may be from you). The message is truncated. Truncation can use ellipses.
    - [ ] If the last message is unread, it should be bold or otherwise emphasized.
- [ ] When the chat bar is closed, the messages should not be visible.
- [ ] As new messages come in through the web socket, the list is updated.

### Chat Sidebar Current Conversation Section
- [ ] When a new conversation is started, or an old conversation is active, the Current Conversation Section is shown.
- [ ] The avatar and handle or guid of the person being chatted with is shown.
    - [ ] The avatar and handle/guid should be clickable, and will load that user's user page.
- [ ] The messages in the conversation are shown, with the sender's avatar next to each message. The user's own messages should be aligned to the right, the other participant's to the left.
    - [ ] Each message shows how long ago it was sent, based on its timestamp.
        - if possible, messages that are less than 1 minute apart should have a single timestamp for the entire group, below the group.
    - [ ] If a handle with an @ is in a message, it should automatically be formatted as a clickable link to that handle
    - [ ] If a link (http, https, ftp) is in a message, it should automatically be formatted as a clickable external link.
    - [ ] If a ob link is in a message, it should automatically be formatted as a clickable internal link.
    - [ ] The avatar and handle/guid should be clickable, and will load that user's user page.
    - [ ] New messages will come in through a web socket with a peerID (guid), and should immediately be shown in the current conversation. 
    - [ ] An api call to markchatasread should be sent immediately when each message appears n the Current Conversation Section.
- [ ] Messages scroll if they don't fit in the Current Conversation Section.
- [ ] The messages are fetched in batches, and old messages will lazy load if the user scrolls up.
- [ ] There is a message input field. It should be limited to 20,000 characters.
    - [ ] When the user starts typing, a message should be sent with a blank message value. This will trigger a "typing" indicator for the other user. This should be on a timer, so it shows for X seconds, and at the end of that time another message is sent if the other user is still typing.
- [ ] There is an emoji button next to the message input field. It will show an emoji selection box when clicked, allowing the user to insert an emoji into their conversation.
- [ ] There is a close button, it will close the Current Conversation Section. 
- [ ] There is a more menu, with the option to delete the conversation. 

### User Page Message Button
- [ ] When the message button on the user page is clicked, it should start a new conversation with that user.

## Data
/ob/chatconversations - get all chat conversations as an array, with guid and unread count
/ob/chatconversation - delete one conversation
/ob/chatmessages - get messages for one conversation
/ob/chatmessage - delete one message
/ob/chat - POST the message
/ob/markchatasread

This is the format of messages on the websocket that are relevant to chat:

### Message:
```
{
    "message": {
        "messageId": "KwLwyVgEjP+HHA==",
        "peerId": "QmfCXCN4x7S8A2Ka6ZQisF3kU5bPH8vzV44odLo4mZccaw",
        "subject": "",
        "message": "Hello World!",
        "timestamp": "2017-02-08T15:47:25.562600073-05:00"
    }
}
```

### Message has been read:
```
{
    "messageRead": {
        "messageId": "FHi6CCAjxE59OQ==",
        "peerId": "QmfCXCN4x7S8A2Ka6ZQisF3kU5bPH8vzV44odLo4mZccaw",
        "subject": ""
    }
}
```

### Other user is typing:
```
{
    "messageTyping": {
        "peerId": "QmfCXCN4x7S8A2Ka6ZQisF3kU5bPH8vzV44odLo4mZccaw",
        "subject": ""
    }
}
```

## ToDos
- add a delete button to the conversation to permanently delete the conversation
- change chatconversations api to order the data by latest message (timestamp)
- change chatconversations to include the last message
- design the offscreen unread messages indicators
- design a typing indicator

## ToDo Later (post 2.0)
- design a way to delete a specific message in the chat (locally)
- design a way to delete the entire conversation locally
- consider a way to access an expanded view for the conversation
